# Generated by Django 6.0.4 on 2026-04-28 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Кітап атауы')),
                ('author', models.CharField(max_length=100, verbose_name='Авторы')),
                ('description', models.TextField(verbose_name='Сипаттамасы')),
                ('pdf_link', models.URLField(blank=True, verbose_name='PDF сілтемесі')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main.subject')),
            ],
            options={
                'verbose_name': 'Кітап',
                'verbose_name_plural': 'Кітаптар',
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Формула атауы')),
                ('formula_text', models.CharField(max_length=200, verbose_name='Формула мәтіні')),
                ('description', models.TextField(blank=True, verbose_name='Түсіндірмесі')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='main.subject')),
            ],
            options={
                'verbose_name': 'Формула',
                'verbose_name_plural': 'Формулалар',
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Видео атауы')),
                ('youtube_url', models.URLField(verbose_name='YouTube сілтемесі')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттамасы')),
                ('duration', models.CharField(default='10 мин', max_length=20, verbose_name='Ұзақтығы')),
                ('order', models.IntegerField(default=0, verbose_name='Реттік нөмірі')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.subject')),
            ],
            options={
                'verbose_name': 'Видеосабақ',
                'verbose_name_plural': 'Видеосабақтар',
            },
        ),
    ]
